============================= test session starts ==============================
platform linux -- Python 3.13.2, pytest-8.3.4, pluggy-1.5.0 -- /usr/local/bin/python3.13
cachedir: .pytest_cache
Using --random-order-bucket=global
Using --random-order-seed=481089

rootdir: /sandbox
plugins: cov-6.0.0, mock-3.14.0, random-order-1.1.1
collecting ... collected 2 items

test_bowling.py::test_all_strikes PASSED                                 [ 50%]
test_bowling.py::test_strikes_and_numbers FAILED                         [100%]

=================================== FAILURES ===================================
___________________________ test_strikes_and_numbers ___________________________

    def test_strikes_and_numbers():
>       assert bowling("X|X||X|X|X|X|X|X|X||X6") == 296

test_bowling.py:7: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
bowling.py:10: in bowling
    final_score += compute_X(clean_string, i)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

clean_string = 'XXXXXXXXXX6', i = 9

    def compute_X(clean_string, i):
        score = 10
        next_string = clean_string[i+1]
>       next_next_string = clean_string[i+2]
E       IndexError: string index out of range

bowling.py:19: IndexError
=========================== short test summary info ============================
FAILED test_bowling.py::test_strikes_and_numbers - IndexError: string index o...
========================= 1 failed, 1 passed in 0.11s ==========================
